version: '3.8'
services:
  mysql:
    image: mysql:8.4
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    networks:
      - test-network
    volumes:
      - mysql-data:/var/lib/mysql

  spring:
    image: memo-with-tags:latest
    container_name: memo-app
    restart: on-failure
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/testdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpassword
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    networks:
      - test-network

volumes:
  mysql-data:

networks:
  test-network:
