spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # 기본값 dev
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
        debug: true

springdoc:
  override-with-generic-response: false
# 이후 jwt도 yml에 넣어서 관리 예정