spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: testuser
    password: testpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  config:
    import: "optional:file:.env[.properties]"

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: ERROR
    com.wafflestudio.toyproject.memoWithTags.aspect: INFO
  file:
    name: logs/app.log