name: Kotlin Lint Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v5

      # 2. JDK 환경 설정
      - name: Set up Corretto JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '17'

      # 2. Ktlint 검사 실행
      - name: Run Lint
        run: |
          ./gradlew ktlintCheck
